### ISSUE TITLE
Mod security plugin?

### ISSUE THREAD

**Issue by phillbaker** [debops/ansible-nginx#154]
Hello and thanks for the work on this! What are your thoughts on adding the installation of [modsecurity-nignx](https://github.com/SpiderLabs/ModSecurity-nginx) to this package?

**Comment by drybjed** [comment]
Welcome! The DebOps roles are focused on production environments, which means that direct software compilation on the destiination hosts is discouraged where possible. You should read [DebOps Software Source Policy](https://docs.debops.org/en/latest/debops-policy/docs/software-source-policy.html) if you want to know how the various software packages should be handled.

The `modsecurity-nginx` is an `nginx` module which needs to be compiled in, so it gets a bit complicated. What you could do instead of adding the required steps in this role, is to provide the modifed `nginx` Debian packages through your own local APT repository. You can easily prepare a modified set of `nginx` packages with any modifications that you want this way.

**Comment by phillbaker** [comment]
Makes sense, thanks!
