### ISSUE TITLE
Download nginx package via https

### ISSUE THREAD

**Issue by chris-griffin** [debops/ansible-nginx#158]
We should download nginx via https instead of http

https://github.com/debops/ansible-nginx/blob/master/defaults/main.yml#L55

PR coming

**Comment by drybjed** [comment]
Just to reassure you - the role gets the GPG key for the `nginx` repository via the OpenPGP keyserver network, therefore a third party. The packages are downloaded over HTTP, but the repository GPG key is used by APT to validate them, therefore the download over HTTP doesn't really matter. if you check in `/etc/apt/sources.list`, unless you changed the defaults, the system repositories use HTTP as well.

Since the `nginx` repositories provide the service over HTTPS, we can change the URL here.

**Comment by chris-griffin** [comment]
Thanks for the merge. Yes, agreed it has minimal benefits (privacy being the main one).
