### ISSUE TITLE
Support for let's encrypt

### ISSUE THREAD

**Issue by htgoebel** [debops/ansible-nginx#84]
Maybe this is more an issue for the pki-role?

Please add support for automatically generating keys and getting signed certificates using the EFF's  Let’s Encrypt client. https://letsencrypt.org/

Let’s Encrypt allows getting officially signed certificates for free and within minutes.

If then this would automatically be combined it with HPKP (see #83), it'd be awesome :-)

**Comment by drybjed** [comment]
That would probably need to be its own separate role. I want to split `debops.pki` into smaller roles as well, but we will see.

As for Let's Encrypt support, I have one gripe with them - they want to ascertain that the client calling the service as control over port 443. This is one of the ports that require `root` privileged to be bound to, but not the only one since all ports < 1024 have this requirement. And I know that some of the ports available in this range are unused in the IANA registry. Right now Let's Encrypt conflicts with the webserver, and adding automated support for it is tricky. I hope that in the future LE team will support their own port, which would make things considerably easier.

Anyway, I've found out [a blog entry](https://blog.mister-muffin.de/2015/11/04/let's-encrypt-with-pound-on-debian/) which describes adding support of Let's Encrypt to pound, that might be a good first step to figuring out how to handle the process. Packages required by Let's Encrypt have just been packaged in Debian ([python-acme](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=801356), [python-letsencrypt](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=774387)) so that will help move things along.

And Ansible roles are starting to appear as well: https://github.com/thefinn93/ansible-letsencrypt

**Comment by drybjed** [comment]
Just a heads up, first step to support Let's Encrypt in DebOps has been done - `nginx` is now configured to respond to or redirect ACME challenges: https://github.com/debops/ansible-nginx/pull/91

**Comment by htgoebel** [comment]
Thanks. This looks very promising :-)

**Comment by ypid** [comment]
Issue is resolved by now. Anyone wants to close it :wink: ?
